apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  selector:
    app: webui
  replicas: 5
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.15
          ports:
            - containerPort: 80
