apiVersion: v1
kind: Pod
metadata:
  name: mysql-env-pod
spec:
  containers:
    - name: mysql-container
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"